version: 2

models:
  - name: campaign_inventory_model
    description: "This table holds a a campaign historical performance dataset."
    columns:
      - name: type
        description: "Engagement types"
        tests: 
          - not_null

  - name: global_design_model
    description: "This table holds data analyzed from advertisements using computer vision."
    columns:
      - name: game_key
        description: "A unique identifier that identifies a particular creative."
        test:
          - unique
          - not_null

  - name: briefing_model
    description: "This table holds campaign & creative plan data."
    columns:
      - name: campaign_id_br
        description: "A unique identifier of a campaign."
        tests:
          - not_null
          - unique

  - name: full_ad_data
    description: "A joined Ads data table that contains campaigns_inventory, briefing, and global_design tables data"
    columns:
      - name: campaign_id
        description: "A unique identifier of a campaign"
        tests:

  

  